// app/layout.tsx
import "@/app/globals.css";
import type { Metadata } from "next";
import Footer from "@/components/AppFooter";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-black text-white">
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
