// app/layout.tsx
import "@/app/globals.css";
import type { Metadata } from "next";
import Footer from "@/components/app_details/AppFooter";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <div>

      <main className="flex-grow">{children}</main>
      <Footer />
    </div>
  
  );
}
